version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
  AfterInstall:
  ApplicationStart:
    - location: start-server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop-server.sh
      timeout: 300
      runas: root



