version: 0.2
phases:

  install:
    commands:
      - mvn install

  build:
    commands:
      - mvn clean package

artifacts:
  discard-paths: yes
  name: api-$(date +%Y-%m-%d)
  files:
    - target/demo-0.0.1-SNAPSHOT.war
    - scripts/*.sh
    - appspec.yml

cache:
  paths:
    - '/root/.m2/**/*'
