version: 0.2
phases:
  install:
    commands:
      - mvn install
  build:
    commands:
      - mvn clean package

artifacts:
  discard-paths: yes
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml
  name: spring-boot-api-$(date +%Y-%m-%d).zip

cache:
  paths:
    - '/root/.m2/**/*'
