version: 0.2
phases:

  install:
    commands:
      - mvn install

  build:
    commands:
      - mvn clean package

artifacts:
  discard-paths: yes
  name: api-$(date +%Y-%m-%d)
  files:
    - target/ROOT.jar
cache:
  paths:
    - '/root/.m2/**/*'
